export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL"
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET"

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"
export const ORDER_DETAILS_RESET = "ORDER_DETAILS_RESET"

export const ORDER_USER_REQUEST = "ORDER_USER_REQUEST"
export const ORDER_USER_SUCCESS = "ORDER_USER_SUCCESS"
export const ORDER_USER_FAIL = "ORDER_USER_FAIL"
export const ORDER_USER_RESET = "ORDER_USER_RESET"

export const ORDER_ADMIN_REQUEST = "ORDER_ADMIN_REQUEST"
export const ORDER_ADMIN_SUCCESS = "ORDER_ADMIN_SUCCESS"
export const ORDER_ADMIN_FAIL = "ORDER_ADMIN_FAIL"
export const ORDER_ADMIN_RESET = "ORDER_ADMIN_RESET"

export const ORDER_ADMIN_UPDATE_REQUEST = "ORDER_ADMIN_UPDATE_REQUEST"
export const ORDER_ADMIN_UPDATE_SUCCESS = "ORDER_ADMIN_UPDATE_SUCCESS"
export const ORDER_ADMIN_UPDATE_FAIL = "ORDER_ADMIN_UPDATE_FAIL"
export const ORDER_ADMIN_UPDATE_RESET = "ORDER_ADMIN_UPDATE_RESET"

