export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_RESET = "USER_LOGIN_RESET"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET"

export const USER_ADDRESS_SUCCESS = "USER_ADDRESS_SUCCESS";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET"


export const USERS_ADMIN_REQUEST = "USERS_ADMIN_REQUEST";
export const USERS_ADMIN_SUCCESS = "USERS_ADMIN_SUCCESS";
export const USERS_ADMIN_FAIL = "USERS_ADMIN_FAIL";
export const USERS_ADMIN_RESET = "USERS_ADMIN_RESET"


export const USER_ADMIN_DELETE_REQUEST = "USER_ADMIN_DELETE_REQUEST";
export const USER_ADMIN_DELETE_SUCCESS = "USER_ADMIN_DELETE_SUCCESS";
export const USER_ADMIN_DELETE_FAIL = "USER_ADMIN_DELETE_FAIL";
export const USER_ADMIN_DELETE_RESET = "USER_ADMIN_DELETE_RESET"


export const USER_ADMIN_DETAILS_REQUEST = "USER_ADMIN_DETAILS_REQUEST";
export const USER_ADMIN_DETAILS_SUCCESS = "USER_ADMIN_DETAILS_SUCCESS";
export const USER_ADMIN_DETAILS_FAIL = "USER_ADMIN_DETAILS_FAIL";
export const USER_ADMIN_DETAILS_RESET = "USER_ADMIN_DETAILS_RESET"


export const USER_ADMIN_UPDATE_REQUEST = "USER_ADMIN_UPDATE_REQUEST";
export const USER_ADMIN_UPDATE_SUCCESS = "USER_ADMIN_UPDATE_SUCCESS";
export const USER_ADMIN_UPDATE_FAIL = "USER_ADMIN_UPDATE_FAIL";
export const USER_ADMIN_UPDATE_RESET = "USER_ADMIN_UPDATE_RESET"


